site_name: Crowdsec
nav:
  - Home: index.md
  - Crowdsec v1.0: "!include ./docs/v1.0.X/mkdocs.yml"
  - Crowdsec v1.1 : "!include ./docs/v1.1.X/mkdocs.yml"
  - API Swagger : https://crowdsecurity.github.io/api_doc/index.html?urls.primaryName=LAPI" target="_blank
  - Hub : https://hub.crowdsec.net/" target="_blank
  - Releases : https://github.com/crowdsecurity/crowdsec/releases" target="_blank
  - Contributing:
    - Guide: contributing.md
  - FAQ:
    - Questions: faq.md


markdown_extensions:
  - codehilite:
      guess_lang: false
  - toc:
      permalink: true
  - admonition
theme: 
  name: material
  logo: assets/images/crowdsec2.png
  favicon: assets/images/crowdsec2.png
  features:
    - navigation.tabs
    - navigation.expand
    - navigation.instant
    - navigation.section
  palette:
    primary: "#3d85c6" 
  language: en
  font:
    text: Montserrat
  highlightjs: true
  hljs_languages:
      - yaml
repo_url: https://github.com/crowdsecurity/crowdsec
repo_name: GitHub
plugins:
    - search
    - macros
    - monorepo

extra:
    swagger_url: "https://raw.githubusercontent.com/crowdsecurity/crowdsec/master/pkg/models/localapi_swagger.yaml"
    v10X:
      doc:
          new_issue: "[new documentation issue](https://github.com/crowdsecurity/crowdsec/issues/new)"
          discourse: "[CrowdSecurity discourse](http://discourse.crowdsec.net)"
          gitter: "[Crowdsec gitter](http://discourse.crowdsec.net)"
      hub:
          name: Crowdsec Hub
          htmlname: "[Crowdsec Hub](https://hub.crowdsec.net/)"
          url: "https://hub.crowdsec.net/"
          plugins_url: "https://hub.crowdsec.net/browse/#bouncers"
          scenarios_url: "https://hub.crowdsec.net/browse/#configurations"
          parsers_url: "https://hub.crowdsec.net/browse/#configurations"
          collections_url: "https://hub.crowdsec.net/browse/#collections"
      crowdsec:
          name: Crowdsec
          Name: Crowdsec
          bin: crowdsec-agent
          path: /usr/bin/crowdsec-agent
          url: https://github.com/crowdsecurity/crowdsec
          bugreport: "https://github.com/crowdsecurity/crowdsec/issues"
          main_log: "/var/log/crowdsec.log"
          download_url: https://github.com/crowdsecurity/crowdsec/releases
      cli:
          name: cscli
          Name: cscli
          main_doc: /Crowdsec/v10/cscli/cscli/
          url: "https://github.com/crowdsecurity/crowdsec"
          bugreport: "https://github.com/crowdsecurity/crowdsec/issues"
      lapi:
          name: local API (LAPI)
          Name: Local API (LAPI)
          Htmlname: "[Local API](/Crowdsec/v10/localAPI/)"
          htmlname: "[local API](/Crowdsec/v10/localAPI/)"
          url: /Crowdsec/v11/localAPI/
          swagger: https://crowdsecurity.github.io/api_doc/index.html?urls.primaryName=LAPI

        #   alerts_doc: /Crowdsec/v1/cscli/cscli_alerts/
        #   decisions_doc: /Crowdsec/v1/cscli/cscli_decisions/
        #   collections_doc: /Crowdsec/v1/cscli/cscli_collections/
        #   parsers_doc: /Crowdsec/v1/cscli/cscli_parsers/
        #   scenarios_doc: /Crowdsec/v1/cscli/cscli_scenarios/
        
        #   api_doc: /Crowdsec/v0/cscli/cscli_api/
        #   ban_doc: /Crowdsec/v0/cscli/cscli_ban/
        #   metrics_doc: /Crowdsec/v0/cscli/cscli_metrics/
        #   remove_doc: /Crowdsec/v0/cscli/cscli_remove/
        #   install_doc: /Crowdsec/v0/cscli/cscli_install/
        #   list_doc: /Crowdsec/v0/cscli/cscli_list/
        #   update_doc: /Crowdsec/v0/cscli/cscli_update/
        #   upgrade_doc: /Crowdsec/v0/cscli/cscli_upgrade/
        #   backup_doc: /Crowdsec/v0/cscli/cscli_backup/
        #   simulation_doc: /Crowdsec/v0/cscli/cscli_simulation/
      config:
          cli_dir: /etc/crowdsec/cscli/
          crowdsec_dir: "/etc/crowdsec/config/"
          acquis_path: "/etc/crowdsec/config/acquis.yaml"
      bouncers:
          name: bouncers
          Name: bouncers
          url: "https://hub.crowdsec.net/browse/#bouncers"
          htmlname: "[bouncers](/Crowdsec/v10/bouncers/)"
          Htmlname: "[Bouncers](/Crowdsec/v10/bouncers/)"
      plugins:
          name: backend plugins
          configpath: "/etc/crowdsec/plugins/backend/"
          binpath: "/usr/local/lib/crowdsec/plugins/"
      metabase:
          name: metabase
          url: https://github.com/crowdsecurity/crowdsec
      wizard:
          name: wizard
          url: "https://github.com/crowdsecurity/crowdsec"
          bin: "./wizard.sh"
          bugreport: "https://github.com/crowdsecurity/crowdsec/issues"
      ref:
          parser: "[parser](/Crowdsec/v10/references/parsers/)"
          Parser: "[Parser](/Crowdsec/v10/references/parsers/)"
          scenario: "[scenarios](/Crowdsec/v10/references/scenarios/)"
          Scenario: "[Scenarios](/Crowdsec/v10/references/scenarios/)"
          acquis: "[acquisition](/Crowdsec/v10/guide/crowdsec/acquisition/)"
          Acquis: "[Acquisition](/Crowdsec/v10/guide/crowdsec/acquisition/)"
          output: "[output](/Crowdsec/v10/references/output/)"
          Output: "[Output](/Crowdsec/v10/references/output/)"
  # All the technical terms
      event:
          name: event
          Name: Event
          htmlname: "[event](/Crowdsec/v10/getting_started/concepts/#event)"
          Htmlname: "[Event](/Crowdsec/v10/getting_started/concepts/#event)" 
      expr:
          name: expr
          Name: Expr
          htmlname: "[expr](/Crowdsec/v10/write_configurations/expressions/)"
          Htmlname: "[Expr](/Crowdsec/v10/write_configurations/expressions/)"
      filter:
          name: filter
          Name: Filter
          htmlname: "[filter](/Crowdsec/v10/references/parsers/#filter)"
          Htmlname: "[Filter](/Crowdsec/v10/references/parsers/#filter)"
      onsuccess:
          name: onsuccess
          Name: Onsuccess
          htmlname: "[onsuccess](/Crowdsec/v10/references/parsers/#onsuccess)"  
          Htmlname: "[Onsuccess](/Crowdsec/v10/references/parsers/#onsuccess)"  
      statics:
          name: statics
          Name: Statics
          htmlname: "[statics](/Crowdsec/v10/references/parsers/#statics)"
          Htmlname: "[Statics](/Crowdsec/v10/references/parsers/#statics)"
      profiles:
          htmlname: "[profiles](/Crowdsec/v10/references/profiles/)"
      simulation:
          htmlname: "[profiles](/Crowdsec/v10/references/simulation/)"
      parsers:
          name: parsers
          Name: Parsers
          htmlname: "[parsers](/Crowdsec/v10/getting_started/concepts/#parsers)"
          Htmlname: "[Parsers](/Crowdsec/v10/getting_started/concepts/#parsers)"
      scenarios:
          name: scenarios
          Name: Scenarios
          htmlname: "[scenarios](/Crowdsec/v10/getting_started/concepts/#scenarios)"
          Htmlname: "[Scenarios](/Crowdsec/v10/getting_started/concepts/#scenarios)"
      collections:
          name: collections
          Name: Collections
          htmlname: "[collections](/Crowdsec/v10/getting_started/concepts/#collections)"
          Htmlname: "[Collections](/Crowdsec/v10/getting_started/concepts/#collections)"
      timeMachine:
          name: timeMachine
          Name: TimeMachine
          htmlname: "[timeMachine](/Crowdsec/v10/getting_started/concepts/#timemachine)"
          Htmlname: "[TimeMachine](/Crowdsec/v10/getting_started/concepts/#timemachine)"
      alert:
          name: alert
          Name: Alert
          htmlname: "[alert](/Crowdsec/v10/getting_started/concepts/#alerts)"
          Htmlname: "[Alert](/Crowdsec/v10/getting_started/concepts/#alerts)"
      decision:
          name: decision
          Name: Decision
          htmlname: "[decision](/Crowdsec/v10/getting_started/concepts/#decisions)"
          Htmlname: "[Decision](/Crowdsec/v10/getting_started/concepts/#decisions)"
      overflow:
          name: overflow
          Name: Overflow
          htmlname: "[overflow](/Crowdsec/v10/getting_started/concepts/#overflow-or-signaloccurence)"
          Htmlname: "[Overflow](/Crowdsec/v10/getting_started/concepts/#overflow-or-signaloccurence)"
      whitelists:
          name: whitelists
          Name: Whitelists
          htmlname: "[whitelists](/Crowdsec/v10/write_configurations/whitelist/)"
          Htmlname: "[Whitelists](/Crowdsec/v10/write_configurations/whitelist/)"
      signal:
          name: signal
          Name: Signal
          htmlname: "[signal](/Crowdsec/v10/getting_started/concepts/#overflow-or-signaloccurence)"
          Htmlname: "[Signal](/Crowdsec/v10/getting_started/concepts/#overflow-or-signaloccurence)"
  #scenario stuff
      stage:
          name: stage
          Name: Stage
          htmlname: "[stage](/Crowdsec/v10/getting_started/concepts/#stages)"
          Htmlname: "[Stage](/Crowdsec/v10/getting_started/concepts/#stages)"
      leakspeed:
          name: leakspeed
          Name: Leakspeed
          htmlname: "[leakspeed](/Crowdsec/v10/references/scenarios/#leakspeed)"
          Htmlname: "[Leakspeed](/Crowdsec/v10/references/scenarios/#leakspeed)"
      capacity:
          name: capacity
          Name: Capacity
          htmlname: "[capacity](/Crowdsec/v10/references/scenarios/#capacity)"
          Htmlname: "[Capacity](/Crowdsec/v10/references/scenarios/#capacity)"
      duration:
          name: duration
          Name: Duration
          htmlname: "[duration](/Crowdsec/v10/references/scenarios/#duration)"
          Htmlname: "[Duration](/Crowdsec/v10/references/scenarios/#duration)"
      prometheus:
          name: prometheus
          htmlname: "[prometheus](https://github.com/prometheus/client_golang)"
      api:
          name: API
          htmlname: "[API](TBD)"
          topX:
              name: topX
              htmlname: "[topX](TBD)"
###############################################################
### Bellow are defines for V1 and later of the documentation ##
###############################################################
    v11X:
      doc:
          new_issue: "[new documentation issue](https://github.com/crowdsecurity/crowdsec/issues/new)"
          discourse: "[CrowdSecurity discourse](http://discourse.crowdsec.net)"
          community: "[community](http://discourse.crowdsec.net)"
      hub:
          name: Crowdsec Hub
          htmlname: "[Crowdsec Hub](https://hub.crowdsec.net/)"
          url: "https://hub.crowdsec.net/"
          bouncers_url: "https://hub.crowdsec.net/browse/#bouncers"
          scenarios_url: "https://hub.crowdsec.net/browse/#configurations"
          parsers_url: "https://hub.crowdsec.net/browse/#configurations"
          collections_url: "https://hub.crowdsec.net/browse/#collections"
      crowdsec:
          name: crowdsec-agent
          Name: Crowdsec-agent
          url: https://github.com/crowdsecurity/crowdsec
          bugreport: "https://github.com/crowdsecurity/crowdsec/issues"
          download_url: https://github.com/crowdsecurity/crowdsec/releases
      lapi:
          name: local API (LAPI)
          Name: Local API (LAPI)
          Htmlname: "[Local API](/Crowdsec/v11/localAPI/)"
          htmlname: "[local API](/Crowdsec/v11/localAPI/)"
          url: /Crowdsec/v11/localAPI/
          swagger: https://crowdsecurity.github.io/api_doc/index.html?urls.primaryName=LAPI
      cli:
          name: cscli
          Name: Cscli
          bin: cscli
          user_guide: "[cscli](/Crowdsec/v11/user_guide/cscli/)"
      config:
          crowdsec_dir: "/etc/crowdsec/"
          acquis_path: "/etc/crowdsec/acquis.yaml"
          crowdsec_config_file: "/etc/crowdsec/config.yaml"
      bouncers:
          name: bouncers
          Name: Bouncers
          url: "https://hub.crowdsec.net/browse/#bouncers"
          htmlname: "[bouncers](/Crowdsec/v11/bouncers/)"
          Htmlname: "[bouncers](/Crowdsec/v11/bouncers/)"
      metabase:
          name: metabase
          htmlName: "[dashboard](/Crowdsec/v11/observability/dashboard)"
      wizard:
          name: wizard
          bin: "./wizard.sh"
          bugreport: "https://github.com/crowdsecurity/crowdsec/issues"
      ref:
          acquis: "[acquisition](/Crowdsec/v11/user_guide/configurations_management/acquisition/)"
          parsers: "[parsers](/Crowdsec/v11/references/parsers/)"
          scenarios: "[scenarios](/Crowdsec/v11/references/scenarios/)"   
  # All the technical terms
      event:
          name: event
          Name: Event
          htmlname: "[event](/Crowdsec/v11/getting_started/concepts/#events)"
          Htmlname: "[Event](/Crowdsec/v11/getting_started/concepts/#events)" 
      expr:
          name: expr
          Name: Expr
          htmlname: "[expr](/Crowdsec/v11/references/expressions/)"
          Htmlname: "[Expr](/Crowdsec/v11/references/expressions/)"
      filter:
          name: filter
          Name: Filter
          htmlname: "[filter](/Crowdsec/v11/references/parsers/#filter)"
          Htmlname: "[Filter](/Crowdsec/v11/references/parsers/#filter)"
      onsuccess:
          name: onsuccess
          Name: Onsuccess
          htmlname: "[onsuccess](/Crowdsec/v11/references/parsers/#onsuccess)"  
          Htmlname: "[Onsuccess](/Crowdsec/v11/references/parsers/#onsuccess)"  
      profiles:
          htmlname: "[profiles](/Crowdsec/v11/references/profiles/)"
      simulation:
          htmlname: "[profiles](/Crowdsec/v11/references/simulation/)"
      statics:
          name: statics
          Name: Statics
          htmlname: "[statics](/Crowdsec/v11/references/parsers/#statics)"
          Htmlname: "[Statics](/Crowdsec/v11/references/parsers/#statics)"
      parsers:
          name: parsers
          Name: Parsers
          htmlname: "[parsers](/Crowdsec/v11/getting_started/concepts/#parsers)"
          Htmlname: "[Parsers](/Crowdsec/v11/getting_started/concepts/#parsers)"
      scenarios:
          name: scenarios
          Name: Scenarios
          htmlname: "[scenarios](/Crowdsec/v11/getting_started/concepts/#scenarios)"
          Htmlname: "[Scenarios](/Crowdsec/v11/getting_started/concepts/#scenarios)"
      collections:
          name: collections
          Name: Collections
          htmlname: "[collections](/Crowdsec/v11/getting_started/concepts/#collections)"
          Htmlname: "[Collections](/Crowdsec/v11/getting_started/concepts/#collections)"
      timeMachine:
          name: timeMachine
          Name: TimeMachine
          htmlname: "[timeMachine](/Crowdsec/v11/getting_started/concepts/#timemachine)"
          Htmlname: "[TimeMachine](/Crowdsec/v11/getting_started/concepts/#timemachine)"
      alert:
          name: alert
          Name: Alert
          htmlname: "[alert](/Crowdsec/v11/getting_started/concepts/#alerts)"
          Htmlname: "[Alert](/Crowdsec/v11/getting_started/concepts/#alerts)"
      decision:
          name: decision
          Name: Decision
          htmlname: "[decision](/Crowdsec/v11/getting_started/concepts/#decisions)"
          Htmlname: "[Decision](/Crowdsec/v11/getting_started/concepts/#decisions)"
      whitelists:
          name: whitelists
          Name: Whitelists
          htmlname: "[whitelists](/Crowdsec/v11/write_configurations/whitelist/)"
          Htmlname: "[Whitelists](/Crowdsec/v11/write_configurations/whitelist/)"
     #scenario stuff
      stage:
          name: stage
          Name: Stage
          htmlname: "[stage](/Crowdsec/v11/getting_started/concepts/#stages)"
          Htmlname: "[Stage](/Crowdsec/v11/getting_started/concepts/#stages)"
      leakspeed:
          name: leakspeed
          Name: Leakspeed
          htmlname: "[leakspeed](/Crowdsec/v11/references/scenarios/#leakspeed)"
          Htmlname: "[Leakspeed](/Crowdsec/v11/references/scenarios/#leakspeed)"
      capacity:
          name: capacity
          Name: Capacity
          htmlname: "[capacity](/Crowdsec/v11/references/scenarios/#capacity)"
          Htmlname: "[Capacity](/Crowdsec/v11/references/scenarios/#capacity)"
      duration:
          name: duration
          Name: Duration
          htmlname: "[duration](/Crowdsec/v11/references/scenarios/#duration)"
          Htmlname: "[Duration](/Crowdsec/v11/references/scenarios/#duration)"
      prometheus:
          name: prometheus
          htmlname: "[prometheus](https://github.com/prometheus/client_golang)"
      api:
          name: API
          htmlname: "[API](TBD)"
          topX:
              name: topX
              htmlname: "[topX](TBD)"

